jobs:

- name: infra-provision
  type: runSh
  steps:
    - IN: VT2_ciRepo
    - TASK:
      - script: ls
  on_success:
    - NOTIFY: slackNotification
    - NOTIFY: myEmail

- name: VT2_runCI
  type: runCI
  steps:
    - IN: VT1_ciRepo
