jobs:

- name: infra-provision
  type: runSh
  steps:
    - IN: coretest_matrixbuildJav_ciRepo
    - TASK:
      - script: ls
  on_success:
    - NOTIFY: slackNotification
    - NOTIFY: myEmail

- name: coretest_matrixbuildJav_runCI
  type: runCI
  steps:
    - IN: coretest_matrixbuildJav_ciRepo
