triggers:
   - name: ecs-tg1
     type: trigger
     version:
       counter: 0
       
   - name: ecs-tg2
     type: trigger
     version:
       counter: 0
       
   - name: ecs-tg3
     type: trigger
     version:
       counter: 0
       
   - name: ecs-tg4
     type: trigger
     version:
       counter: 0
       
   - name: ecs-tg5
     type: trigger
     version:
       counter: 0
