jobs:

- name: infra-provision
  type: runSh
  steps:
    - IN: VT1_ciRepo
    - TASK:
      - script: ls
  on_success:
    - NOTIFY: slackNotification
    - NOTIFY: myEmail

- name: VT1_runCI
    type: runCI
    steps:
      - IN: VT1_ciRepo
