jobs:

#RELEASE

  #- name: flsv-release
   # type: release
    #steps:
     # - IN: flsv-version
        #versionName: testrelease
     # - TASK: managed
      #  bump: beta
      #- IN: flsv-man1
      #- IN: flsv-tg2
   # flags:
    #  - flsv-release
      
#MANIFESTS
      
  - name: flsv-man1
    type: manifest
    steps:
      - IN: flsv-img1
       # versionNumber: 100
      - IN: flsv-tg1
      
  #- name: flsv-man2multiimg
   # type: manifest
    #steps:
     # - IN: flsv-img2
      #- IN: flsv-img5workingdir
      #- IN: fltpsv-dopts2
      #- IN: flecssv-dopts4
       # applyTo:
        #  - flsv-img2
     # - IN: flsv-tg2
      
 # - name: flsv-man3env
  #  type: manifest
   # steps:
    #  - IN: flsv-img3env
     # - IN: flsv-params1
     # - IN: fl-params2
      #- IN: flsv-tg3
      
  - name: flsv-man4entrypoint
    type: manifest
    steps:
      - IN: flsv-img4entrypoint
      - TASK: managed
      - IN: flsv-tg4
      
  - name: flsv-man5driftking
    type: manifest
    steps:
      - IN: flsv-img5workingdir
      - IN: flsv-tg5
      - TASK: managed
  
  - name: flsv-man6redismftomf
    type: manifest
    steps:
      - IN: flsv-img6redis
      - IN: flsv-man1
        switch: off
      
 # - name: flsv-man7invalid
   # type: manifest
    #steps:
     # - IN: flsv-img1
    #  - IN: fl-dopts6invalid
      #- IN: flsv-tg7
      
 # - name: flsv-man8
  #  type: manifest
   # steps:
    #  - IN: flsv-img9
    #  - IN: flsv-dopts6invalid
     # - IN: flsv-tg8
      
  #- name: flsv-man9
   # type: manifest
    #steps:
     # - IN: flsv-img9
    #  - IN: flsv-dopts6invalid
      #- IN: flsv-tg9
      
  #- name: flsv-man10deployall
   # type: manifest
    #steps:
     # - IN: flsv-img8
    #  - IN: flsv-dopts6invalid
     # - IN: flsv-tg10

# DEPLOYMENTS 

 # - name: flsv-ecsdeployup
  #  type: deploy
   # steps:
    #  - IN: flsv-man10deployall
     # - IN: flsv-ecscluster
      #- TASK: managed
       # deployMethod: upgrade
      
  #- name: flsv-ecsdeploybg
   # type: deploy
    #steps:
     # - IN: flsv-man4entrypoint
      #- IN: flecssv-dopts4
      #- IN: flsv-ecscluster
      
  #- name: flsv-ecsdeployupmftomf
   # type: deploy
    #steps:
     # - IN: flsv-man6redismftomf
    #  - IN: flsv-ecscluster
     # - TASK: managed
       # deployMethod: upgrade
        
 # - name: flsv-ecsdeploybginvalid
  #  type: deploy
   # steps:
    #  - IN: flsv-man7invalid
     # - IN: flsv-ecscluster
      
#  - name: flsv-ecsdeployuppm6436
 #   type: deploy
  #  steps:
   #   - IN: flsv-man8
    #  - IN: flsv-ecscluster
     # - TASK: managed
      #  deployMethod: upgrade
      
  #- name: fl-tpdeployup
   # type: deploy
    #steps:
     # - IN: fl-man10deployall
      #- IN: fltp-dopts1
      #- IN: fl-tripubcluster
    #  - TASK: managed
     #   deployMethod: upgrade
      
  - name: flsv-tpdeploybg
    type: deploy
    steps:
      - IN: flsv-man4entrypoint
        switch: off
      #- IN: flsv-tripubcluster
      
 # - name: fl-gkedeployup
  #  type: deploy
   # steps:
    #  - IN: fl-man10deployall
      #- IN: flgke-dopts3
     # - IN: fl-gkecluster
      #- TASK: managed
       # deployMethod: upgrade
      
  #- name: fl-gkedeploybg
   # type: deploy
    #steps:
     # - IN: fl-man5driftking
    #  - IN: flgke-dopts3
     # - IN: fl-gkecluster
      
 # - name: fl-dcldeploy
  #  type: deploy
   # steps:
    #  - IN: fl-man10deployall
     # - IN: fl-dclcluster
        
#  - name: fl-ddcdeploy
 #   type: deploy
  #  steps:
   #   - IN: fl-man10deployall
    #  - IN: fl-ddccluster
      
#runSh
  - name: flsv-inrunsh
    type: runSh
    steps:
      - IN: flsv-sample-script1
        #versionName: "149dc247602ba40192703b5fe0a1bfae01bd8490"
      - IN: flsv-tg2
      - IN: flsv-img1
      - IN: flsv-man1
      - TASK:
        - script: ls
        - script: ./IN/flsv-sample-script1/gitRepo/echo.sh
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: cat IN/fl-man1/integration.json
       # - script: export versionName=$(cat ./IN/fl-img1/version.json | jq -r '.version.versionName')
        - script: . IN/fl-sample-script1/gitRepo/echo.sh
        
  # - name: flsv-inrunsh2
  #   type: runSh
  #   steps:
  #     - IN: flsv-sample-script2
  #     - IN: flsv-tg6
  #     - TASK:
  #       - script: ls
        # - script: ./IN/flsv-sample-script2/gitRepo/echo.sh
        
#rSync
#  - name: fl-rsyncjob
 #   type: rSync
  #  steps:
   #   - IN: "flsr_sample-fleming_sr-rsync"
    #  - IN: fl-tg6
