jobs:
#MANIFESTS
      
  - name: ecs-man1
    type: manifest
    steps:
      - IN: ecs-img1
      - IN: ecs-tg1
      
  - name: ecsman2-invalidimg
    type: manifest
    steps:
      - IN: ecsimg4-tagdoesntexist
      - IN: ecs-tg2
      
  - name: ecsman3-invalid
    type: manifest
    steps:
      - IN: ecs-img2
        versionNumber: 369
      - IN: ecs-tg3

# DEPLOYMENTS 

  - name: ecs-deploy1up
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade
      
  - name: ecs-deploy2bginvalidclu
    type: deploy
    steps:
      - IN: ecs-man1
      - IN: ecsclu2-invalidclu
      
  - name: ecs-deploy3upinvalidimg
    type: deploy
    steps:
      - IN: ecsman2-invalidimg
      - IN: ecs-cluster
      - TASK: managed
        deployMethod: upgrade

  - name: ecs-deploy4bgmani
    type: deploy
    steps:
      - IN: ecsman3-invalid
      - IN: ecs-cluster
